# Copyright (c) 2016 Mirants Lu. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file. 

#--------------------------------------------------------------------
# Uncomment exactly one of the lines labelled (1), (2), and (3) below 
# to switch between compilation modes.
#
# (1) Production use (optimized mode)
      OPT ?= -O2 -DNDEBUG
# (2) Debug mode, w/full line-level debugging symbols
#     OPT ?= -g2
# (3) Profiling mode: opt, but w/debugging symbols
#     OPT ?= -O2 -g2 -DNDEBUG
#--------------------------------------------------------------------

# detect what platform we're building on
$(shell CC="$(CC)" CXX="$(CXX)" TARGET_OS="$(TARGET_OS)" \
  ./build_detect_platform build_config.mk ./)

# this  file is generated by the previous line to set build flags and sources
include build_config.mk

TESTS = \
	paxos/paxos_test \

# Put the object files in a subdirectory, but the application at the top of 
# the object dir
PROGNAMES := $(notdir $(TESTS) $(UTILS))

CFLAGS += -I. -I./include $(PLATFORM_CCFLAGS) $(OPT)
CXXFLAGS += -I. -I./include $(PLATFORM_CXXFLAGS) $(OPT)

LDFLAGS += $(PLATFORM_LDFLAGS)
LIBS += $(PLATFORM_LIBS)

STATIC_OUTDIR = out-static
SHARED_OUTDIR = out-shared

STATIC_PROGRAMS := $(addprefix $(STATIC_OUTDIR)/, $(PROGNAMES))

STATIC_LIBOBJECTS := $(addprefix $(STATIC_OUTDIR)/, $(SOURCES:.cc=.o)) 

SHARED_LIBOBJECTS := $(addprefix $(SHARED_OUTDIR)/, $(SOURCES:.cc=.o))

STATIC_TESTOBJS := $(addprefix $(STATIC_OUTDIR)/, $(addsuffix .o, $(TESTS)))

STATIC_ALLOBJS := $(STATIC_LIBOBJECTS) $(STATIC_TESTOBJS) 

SHARED_ALLOBJS := $(SHARED_LIBOBJECTS)  

default: all 

SHARED_VERSION_MAJOR = 1
SHARED_VERSION_MINOR = 2
SHARED_LIB1 = libskywalker.$(PLATFORM_SHARED_EXT)
SHARED_LIB2 = $(SHARED_LIB1).$(SHARED_VERSION_MAJOR)
SHARED_LIB3 = $(SHARED_LIB1).$(SHARED_VERSION_MAJOR).$(SHARED_VERSION_MINOR)
SHARED_LIBS = $(SHARED_OUTDIR)/$(SHARED_LIB1) $(SHARED_OUTDIR)/$(SHARED_LIB2) $(SHARED_OUTDIR)/$(SHARED_LIB3)
$(SHARED_OUTDIR)/$(SHARED_LIB1): $(SHARED_OUTDIR)/$(SHARED_LIB3)
	ln -fs $(SHARED_LIB3) $(SHARED_OUTDIR)/$(SHARED_LIB1)
$(SHARED_OUTDIR)/$(SHARED_LIB2): $(SHARED_OUTDIR)/$(SHARED_LIB3)
	ln -fs $(SHARED_LIB3) $(SHARED_OUTDIR)/$(SHARED_LIB2)

$(SHARED_OUTDIR)/$(SHARED_LIB3): $(SHARED_LIBOBJECTS)
	$(CXX) $(LDFLAGS) $(PLATFORM_SHARED_LDFLAGS)$(SHARED_LIB2) $(SHARED_LIBOBJECTS) -o $(SHARED_OUTDIR)/$(SHARED_LIB3) $(LIBS)

all: $(SHARED_LIBS) $(STATIC_OUTDIR)/libskywalker.a $(STATIC_PROGRAMS)

check: $(STATIC_PROGRAMS)      
	for t in $(notdir $(TESTS)); do echo "***** Running $$t"; $(STATIC_OUTDIR)/$$t || exit 1; done

clean:
	-rm -rf out-static out-shared
	-rm -f build_config.mk
	-rm -f ./proto/*.pb.*

$(STATIC_OUTDIR):
	mkdir $@

$(STATIC_OUTDIR)/log: | $(STATIC_OUTDIR)
	mkdir $@

$(STATIC_OUTDIR)/machine: | $(STATIC_OUTDIR)
	mkdir $@

$(STATIC_OUTDIR)/network: | $(STATIC_OUTDIR)
	mkdir $@

$(STATIC_OUTDIR)/storage: | $(STATIC_OUTDIR)
	mkdir $@

$(STATIC_OUTDIR)/paxos: | $(STATIC_OUTDIR)
	mkdir $@

$(STATIC_OUTDIR)/util: | $(STATIC_OUTDIR)
	mkdir $@

$(STATIC_OUTDIR)/proto: | $(STATIC_OUTDIR)
	mkdir $@

.PHONY: STATIC_OBJDIRS
STATIC_OBJDIRS: \
  $(STATIC_OUTDIR)/log \
  $(STATIC_OUTDIR)/machine \
  $(STATIC_OUTDIR)/network \
  $(STATIC_OUTDIR)/storage \
  $(STATIC_OUTDIR)/paxos \
  $(STATIC_OUTDIR)/util \
  $(STATIC_OUTDIR)/proto \


$(SHARED_OUTDIR):
	mkdir $@

$(SHARED_OUTDIR)/log: | $(SHARED_OUTDIR)
	mkdir $@

$(SHARED_OUTDIR)/machine: | $(SHARED_OUTDIR)
	mkdir $@

$(SHARED_OUTDIR)/network: | $(SHARED_OUTDIR)
	mkdir $@

$(SHARED_OUTDIR)/storage: | $(SHARED_OUTDIR)
	mkdir $@

$(SHARED_OUTDIR)/paxos: | $(SHARED_OUTDIR)
	mkdir $@

$(SHARED_OUTDIR)/util: | $(SHARED_OUTDIR)
	mkdir $@

$(SHARED_OUTDIR)/proto: | $(SHARED_OUTDIR)
	mkdir $@

.PHONY: SHARED_OBJDIRS
SHARED_OBJDIRS: \
  $(SHARED_OUTDIR)/log \
  $(SHARED_OUTDIR)/machine \
  $(SHARED_OUTDIR)/network \
  $(SHARED_OUTDIR)/storage \
  $(SHARED_OUTDIR)/paxos \
  $(SHARED_OUTDIR)/util \
  $(SHARED_OUTDIR)/proto \

$(STATIC_ALLOBJS): | STATIC_OBJDIRS
$(SHARED_ALLOBJS): | SHARED_OBJDIRS

$(STATIC_OUTDIR)/libskywalker.a:$(STATIC_LIBOBJECTS)
	rm -f $@
	ar -rs $@ $(STATIC_LIBOBJECTS)
	rm -rf ./proto/*.pb.*

$(STATIC_OUTDIR)/paxos_test:paxos/test/paxos_test.cc $(STATIC_LIBOBJECTS)
	$(CXX) $(LDFLAGS) $(CXXFLAGS) paxos/test/paxos_test.cc $(STATIC_LIBOBJECTS) -o $@ $(LIBS)

$(STATIC_OUTDIR)/%.o: %.cc 
	$(CXX) $(CXXFLAGS) -c $< -o $@ 

$(STATIC_OUTDIR)/%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@ 


$(SHARED_OUTDIR)/%.o: %.cc 
	$(CXX) $(CXXFLAGS) $(PLATFORM_SHARED_CFLAGS) -c $< -o $@ 

$(SHARED_OUTDIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PLATFORM_SHARED_CFLAGS) -c $< -o $@
